version: '3.7'
services:
  app:
    image: mitwilsch/toto
    build:
      context: ./
    expose:
      - ${CLIENT_PORT}
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    links:
      - mongodb
    volumes:
      - ./:/usr/src/app
  mongodb:
    image: mongo
