const api = {
  basics: {
    name: 'Mitchell Schooler',
    picture: 'https://avatars1.githubusercontent.com/u/4543761?v=4',
    label: 'Software Developer ',
    headline: 'Perfection is a job never done',
    summary: "Hi, I'm Mitchell! ",
    website: 'http://mitchell.schooler.me',
    blog: null,
    yearsOfExperience: 5,
    id: 'f02ba599-d48e-4828-ad63-a6416eba8de9',
    username: 'mitwilsch',
    karma: 11,
    email: '',
    region: 'Rancho Santa Margarita, CA',
    location: {},
    phone: '',
    followers: 0,
    following: 6,
    profiles: [
      {
        network: 'gitconnected',
        username: 'mitwilsch',
        url: 'https://gitconnected.com/mitwilsch',
      },
      {
        network: 'GitHub',
        username: 'mitwilsch',
        url: 'https://github.com/mitwilsch',
      },
      {
        network: 'Reddit',
        url: 'https://www.reddit.com/user/mitwilsch',
        username: 'mitwilsch',
      },
    ],
  },
  skills: [
    {
      name: 'React',
      level: 'Advanced',
      rating: 4,
      yearsOfExperience: 5,
      keywords: [],
    },
  ],
  projects: [
    {
      name: 'mitchell.schooler.me',
      displayName: 'mitchell.schooler.me',
      summary: 'Personal Website',
      website: 'https://mitchell.schooler.me',
      githubUrl: 'https://github.com/mitwilsch/mitchell.schooler.me',
      primaryLanguage: 'JavaScript',
      languages: ['CSS', 'JavaScript', 'HTML'],
      libraries: ['React Router', 'API', 'Material-UI', 'React', 'SPA'],
      images: [],
      videos: [],
    },
    {
      name: 'stat-monitor',
      displayName: 'stat-monitor',
      summary: 'Stat Monitor - Monitor stats on hosted server',
      website: 'mitwilsch.dev',
      githubUrl: 'https://github.com/mitwilsch/stat-monitor',
      primaryLanguage: 'JavaScript',
      languages: ['JavaScript', 'Dockerfile', 'HTML'],
      libraries: [],
      images: [],
      videos: [],
    },
    {
      name: 'host-router',
      displayName: 'host-router',
      summary: 'Serve multiple Express apps from same host',
      website: '',
      githubUrl: 'https://github.com/mitwilsch/host-router',
      primaryLanguage: 'Dockerfile',
      languages: ['Dockerfile'],
      libraries: [],
      images: [],
      videos: [],
    },
    {
      name: 'toto',
      displayName: 'toto',
      summary: 'Toto - A todo app',
      website: 'https://toto-tasks.myddns.me',
      githubUrl: 'https://github.com/mitwilsch/toto',
      primaryLanguage: 'JavaScript',
      languages: ['CSS', 'HTML', 'JavaScript', 'Dockerfile'],
      libraries: [],
      images: [],
      videos: [],
    },
    {
      name: 'schooler.me',
      displayName: 'schooler.me',
      summary: 'Schooler Family Website',
      website: 'https://schooler.me',
      githubUrl: 'https://github.com/mitwilsch/schooler.me',
      primaryLanguage: 'HTML',
      languages: ['JavaScript', 'HTML'],
      libraries: [],
      images: [],
      videos: [],
    },
  ],
  work: [
    {
      company: "Domino's",
      position: 'Assistant Manager',
      website: '',
      location: 'San Diego, CA',
      summary:
        'Taking a lower role in a new company, I am able to balance responsibilities and time better',
      isCurrentRole: true,
      startDate: '2020-03-01',
      endDate: '',
      start: { year: 2020, month: 3 },
      end: {},
      highlights: [],
    },
    {
      company: "Domino's Pizza",
      position: 'General Manager',
      website: '',
      location: 'Trabuco Canyon',
      summary:
        'Managed all aspects of the business, ex. Hiring/Training, Marketing, Labor and Food Cost',
      isCurrentRole: false,
      startDate: '2017-01-01',
      endDate: '2020-02-01',
      start: { year: 2017, month: 1 },
      end: { year: 2020, month: 2 },
      highlights: [
        'Dramatically improved quality of staff training',
        'Implemented policies to increase workflow, increasing labor efficiency',
      ],
    },
    {
      company: 'White Water Realty',
      position: 'SEO/Web Admin, Office Admin',
      website: 'whitewaterrealty.com',
      location: 'San Clemente, CA',
      summary:
        'Maintained website listings (Realty), managed and improved SEO and marketing campaigns',
      isCurrentRole: false,
      startDate: '2016-01-01',
      endDate: '2018-09-01',
      start: { year: 2016, month: 1 },
      end: { year: 2018, month: 9 },
      highlights: [],
    },
    {
      company: 'Uber',
      position: 'Rideshare Driver',
      website: '',
      location: 'Orange County, CA',
      summary: 'Rideshare driver',
      isCurrentRole: false,
      startDate: '2015-05-01',
      endDate: '2017-12-01',
      start: { year: 2015, month: 5 },
      end: { year: 2017, month: 12 },
      highlights: [
        'Planned optimal routes and schedule according to county-wide demands, putting myself in the top 10% of earners',
      ],
    },
    {
      company: "Papa John's",
      position: 'General Manager',
      website: '',
      location: 'Orange County, CA',
      summary: 'Managed multiple locations',
      isCurrentRole: false,
      startDate: '2013-04-01',
      endDate: '2017-05-01',
      start: { year: 2013, month: 4 },
      end: { year: 2017, month: 5 },
      highlights: [],
    },
    {
      company: 'Membrane Switch and Panel, Inc.',
      position: 'Logistics Manager/I.T. Support',
      website: 'http://www.membraneusa.com/',
      location: 'Costa Mesa, CA',
      summary:
        'Managed shipments, ordered supplies for production, optimized processes',
      isCurrentRole: false,
      startDate: '2011-04-01',
      endDate: '2013-11-01',
      start: { year: 2011, month: 4 },
      end: { year: 2013, month: 11 },
      highlights: [
        'Optimized certification/paperwork process, time to fulfill orders reduced by 250%',
      ],
    },
  ],
  publications: [],
  education: [],
  volunteer: [],
  awards: [],
  languages: [],
  interests: [],
  references: [],
};

export default api;
